### PR TITLE
Platform Configurator deployment

### PR DESCRIPTION
**Pull request by c0c0n3**
This PR completes the deployment of Platform Configurator started by #240. It only adds a few things to #240's features:

- a sealed secret regenerated with the actual Platform Configurator image credentials;
- K8s service descriptor;
- an ArgoCD app for Platform Configurator so we can make ArgoCD automatically manage the deployment.

### CODE REVIEW

**Comment by vcutrona** [comment]
Thanks @c0c0n3 for dealing with my incomplete PR.
I'm trying accessing the platform configurator's docs at https://kitt4sme.collab-cloud.eu/platform-configurator/docs, but something weird happens: I see the AIQuS docs instead of PC one (but AIQuS is not part of the deployed tool... right?)

While if I access a platform configurator endpoint (e.g., https://kitt4sme.collab-cloud.eu/platform-configurator/kits), I'm redirected to https://kitt4sme.collab-cloud.eu/kits with no result. I checked the ingress.yaml file and it seems ok.

**Comment by vcutrona** [comment]
Possibly related to #236

**Comment by c0c0n3** [comment]
I think the problem is #273

**Comment by c0c0n3** [comment]
@rx2dev added some routing for AiQus where he's using plain root paths without prefix. One of them is `/docs`. So I think what's happening when you browse to 

-  https://kitt4sme.collab-cloud.eu/platform-configurator/docs

is that PC redirects you to `/docs` (see #273 about it). Then b/c of the Istio rule @rx2dev added, requests targeting this URL

-  https://kitt4sme.collab-cloud.eu/docs

get dispatched to AiQus.

**Pull request merged**
