### PR TITLE
Deploy a replica of FaMS

### PR DESCRIPTION
**Pull request by vcutrona**
Deploy a single replica of FaMS for May review

### CODE REVIEW

**Comment by c0c0n3** [comment]
@vcutrona is the image public? if not, you'll need to generate an access token in your repo and then put it in our sealed secret as explained in #172.

**Comment by c0c0n3** [comment]
@vcutrona in fact, k8s says the image secret is 191 days old so your repo token might have expired...

```bash
$ kubectl get secret
NAME                     TYPE                                  DATA   AGE
...
fams-image               kubernetes.io/dockerconfigjson        1      191d
...
```

**Comment by vcutrona** [comment]
Thanks @c0c0n3 -- just sent you a new deploy token

**Comment by c0c0n3** [comment]
@vcutrona thanks, I've updated the secret w/ your new token. I'm closing this PR though since I've ported your change over to #232 and added the updated secret there.

**Pull request closed without merging**
