### PR TITLE
Ingress file updated to use port mapping, base file node port removal

### PR DESCRIPTION
**Pull request by RyanKelvinFord**
Node port has been removed and port mapping has been created for the profiler.

### CODE REVIEW

**Comment by c0c0n3** [comment]
@RyanKelvinFord there's a few things I forgot to mention about port-based routing, sorry about that.

If memory serves, we should

#### 1. Expose external port 8080 through Istio
We should add an external port 8080 to our Istio profile, which boils down to adding a stanza similar to this
- https://github.com/c0c0n3/kitt4sme.live/blob/main/deployment/mesh-infra/istio/profile.yaml#L54-L57

Since target port 8080 is taken already (see above stanza), the new stanza could be

```yaml
- port: 3000
   nodePort: 8080
   targetPort: 8081
   name: profilers
```

#### 2. Route inbound HTTP traffic from external port 8080
We should add an Istio Gateway server stanza to be able to route HTTP traffic hitting external port 8080. The new stanza should be similar to this:
- https://github.com/c0c0n3/kitt4sme.live/blob/main/deployment/mesh-infra/routing/ingress.yaml#L11-L16

e.g.

```yaml
  - hosts:
    - "*"
    port:
      name: http-profilers
      number: 8081
      protocol: HTTP
    tls:
      httpsRedirect: false
```

and then down below in the virtual service
- https://github.com/c0c0n3/kitt4sme.live/blob/main/deployment/mesh-infra/routing/ingress.yaml#L37

we need a stanza similar to this

```yaml
    - match:
        - port: 8080
      route:
        - destination:
            host: profilers.default.svc.cluster.local
            port:
              number: 80
```

#### 3. Do the same for HTTPs
What a schlep!

#### 4. Test thoroughly
We should test this setup works on a dev cluster---e.g. using the Multipass VM. When we're 100% confident this works, we can deploy it to collab cloud.

**Comment by c0c0n3** [comment]
@RyanKelvinFord please double-check what the Istio docs have to say about it, don't take my word for it. I haven't tested any of that in my local cluster. Also I've just come across a handy blog post about exposing external ports through an Istio gateway
- https://learncloudnative.com/blog/2022-08-01-istio-gateway

**Comment by c0c0n3** [comment]
@karikolehmainen @RyanKelvinFord @kostasgrevenitis this seems quite a bit of work. Do we need both HTTP and HTTPs for the profilers? How are they going to be used in the May demo? If the profilers can't do SSO, then it's kinda pointless to have HTTPs?

Also to consider: we wouldn't need any of this if we implemented #151. It seems a much cleaner solution to me? There would be no need to fiddle w/ Istio in that case, since we already have the HTTP and HTTPs ports...

**Comment by kostasgrevenitis** [comment]
Http is enough for now

**Pull request merged**
